# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                    : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "pt-BR"
title                    : "Documentação, Modelagem e Conservação do Patrimônio"
title_separator          : "|"
subtitle                 : "Grupo de pesquisa CNPq"
name                     : "LabeUrbe"
description: >-
  Grupo de pesquisa interinstitucional voltado para abordagens
  interdisciplinares na documentação, conservação e valorização do patrimônio
  cultural, com foco na arquitetura tradicional do interior continental do
  Brasil e na construção moderna. Ferramentas e metodologias de análise física,
  modelagem digital, sistemas de informação e gestão.
url                      : "https://dmcpatrimonio.github.io"
baseurl                  : ""
repository               : "dmcpatrimonio/dmcpatrimonio.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/icon.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true
search_full_content      : false
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/assets/images/icon.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "LabeUrbe"
  avatar           : "/assets/images/icon.png"
  bio              : "Laboratório de Estudos da Urbe"
  location         : "Universidade de Brasília"
  email            : "labeurbe@unb.br"
  links:
    #- label: "Email"
      #icon: "fas fa-fw fa-envelope-square"
      #url: "mailto:labeurbe@unb.br"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://labeurbe.unb.br"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dmcpatrimonio"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url : "https://github.com/dmcpatrimonio"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .github
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: Pandoc
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
relative_links:
  enabled                : true
  collections            : true


# Markdown Processing
pandoc:
  extensions:
    - bibliography       : "_data/biblio.yaml"
    - csl                : "_lib/chicago-cv.csl"
    - defaults           : "_spec/defaults.yaml"
    - section-divs
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Sao_Paulo"
date_format: "%d/%m/%Y"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-data
  - jekyll-pandoc
  - jekyll-relative-links
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categoria/
tag_archive:
  type: jekyll-archives
  path: /termo/
year_archive:
  type: jekyll-archives
  path: /ano/
collection_archive:
  type: jekyll-archives
  path: /dados/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - collection
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
    year: archive-taxonomy
    collection: archive-taxonomy
  permalinks:
    category: /categoria/:name/
    tag: /termo/:name/
    year: /ano/:year/
    collection: /dados/:collection/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      show_date          : true
      date_format        : "%d/%m/%Y"
      toc                : true
    # _thing
  - scope:
      path               : ""
      type               : "thing"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/Thing"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
      toc                : true
    # _biblio
  - scope:
      path               : ""
      type               : "creativework"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/CreativeWork"
      type               : "PhysicalObject"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
      toc                : false
    # _event
  - scope:
      path               : ""
      type               : "event"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/Event"
      type               : "Event"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
      toc                : true
    # _grant
  - scope:
      path               : ""
      type               : "grant"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/MonetaryGrant"
      type               : "Event"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
      toc                : true
    # _organization
  - scope:
      path               : ""
      type               : "organization"
    values:
      layout             : "organization"
      itemtype           : "http://schema.org/Organization"
      class              : "AgentClass"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
      toc                : true
    # _person
  - scope:
      path               : ""
      type               : "person"
    values:
      layout             : "single"
      itemtype           : "http://schema.org/Person"
      class              : "Agent"
      author_profile     : true
      read_time          : false
      comments           : false
      share              : true
      related            : false
      toc                : true
    # _project
  - scope:
      path               : ""
      type               : "project"
    values:
      layout             : "organization"
      itemtype           : "http://schema.org/ResearchProject"
      class              : "AgentClass"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
      toc                : true


# Collections
collections:
  posts:
    output   : true
    permalink: /:categories/:title/
  thing:
    output   : true
    permalink: /:collection/:title/
  creativework:
    output   : false
    permalink: /biblio/:title/
    sort_by  : issued[0].year
  event:
    output   : true
    permalink: /:collection/:title/
  grant:
    output   : false
    permalink: /:collection/:title/
    sort_by  : amount.validFrom
  organization:
    output   : true
    permalink: /linha/:title/
    sort_by  : title
  person:
    output   : true
    permalink: /membro/:title/
    sort_by  : title
  project:
    output   : true
    permalink: /projeto/:title/
    sort_by  : title

