# Geral {{{1
# =====
title: Documentação, Modelagem e Conservação do Patrimônio
author:
- name: Grupo de pesquisa
  email: labeurbe@unb.br
description: >-
  Grupo de pesquisa interinstitucional voltado para abordagens
  interdisciplinares na documentação, conservação e valorização do patrimônio
  cultural, com foco na arquitetura tradicional do interior continental do
  Brasil e na construção moderna. Ferramentas e metodologias de análise física,
  modelagem digital, sistemas de informação e gestão.
baseurl: ""
url: "https://dmcpatrimonio.github.io"
lang: pt

# Conteúdo {{{1
# ========
source: ""
header_pages:
  - team.md
  - projetos.md
  - biblio.md

# Collections {{{2
# -----------
collections:
  thing:
    output   : true
    permalink: /:collection/:name
  creativework:
    output   : true
    permalink: /:collection/:name
  event:
    output   : true
    permalink: /:collection/:name
  organization:
    output   : true
    permalink: /:collection/:name
  person:
    output   : true
    permalink: /:collection/:name

# Defaults {{{2
# --------
defaults:
  -
    scope:
      path      : ""
      type      : "thing"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Thing"
  -
    scope:
      path      : ""
      type      : "creativework"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/CreativeWork"
      type      : "PhysicalObject"
  -
    scope:
      path      : ""
      type      : "event"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Event"
      type      : "Event"
  -
    scope:
      path      : ""
      type      : "organization"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Organization"
      class     : "AgentClass"
  -
    scope:
      path      : ""
      type      : "person"
    values:
      layout    : "person"
      itemtype  : "http://schema.org/Person"
      class     : "Agent"

# Template {{{1
# ========
remote_theme: p3palazzo/minima-scholar
minima:
  date_format : "%e %B %Y"
  social_links:
    github    : https://github.com/dmcpatrimonio

# Configurações {{{2
# -------------
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: true
  transliterated_header_ids: true
relative_links:
  enabled: true
  collections: true
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# Plugins {{{1
# =======
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Exclude {{{1
# =======
exclude:
  - lib/
  - spec/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - gemfiles/
  - node_modules/
  - .vendor

# vim: set foldmethod=marker :
