# Geral {{{1
# =====
title: >
  Documentação, Modelagem e Conservação do Patrimônio
subtitle                 : "Grupo de pesquisa CNPq"
description: >-
  Grupo de pesquisa interinstitucional voltado para abordagens
  interdisciplinares na documentação, conservação e valorização do patrimônio
  cultural, com foco na arquitetura tradicional do interior continental do
  Brasil e na construção moderna. Ferramentas e metodologias de análise física,
  modelagem digital, sistemas de informação e gestão.
url                      : "https://dmcpatrimonio.github.io"
baseurl                  : ""

# Site Author {{{1
# ===========
author:
  name             : "LabeUrbe"
  avatar           : "/assets/images/icon.png"
  bio              : "Laboratório de Estudos da Urbe"
  location         : "Universidade de Brasília"
  email            : "labeurbe@unb.br"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:labeurbe@unb.br"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://labeurbe.unb.br"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dmcpatrimonio"

# Reading Files {{{1
# =============
encoding                 : "utf-8"
exclude:
  - .sass-cache
  - .vendor/
  - Gemfile
  - LICENSE
  - Makefile
  - README.md
  - gemfiles/
  - node_modules/
  - package.json
  - package-lock.json
keep_files:
  - .git/
  - .github/

# vim: set foldmethod=marker :
# Template {{{1
# ========
theme                    : "minimal-mistakes-jekyll"

# Minima Settings {{{2
# ---------------
#email                    : "labeurbe@unb.br"
#github_username          : dmcpatrimonio # Minima Theme
#header_pages:
  #- about.md
  #- team.md
  #- linhas.md
  #- biblio.md
#lang: pt

# Minimal Mistakes Settings {{{2
# -------------------------
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : false
breadcrumbs              : true
locale                   : "pt-BR"
logo                     : "/assets/images/icon.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
minimal_mistakes_skin    : "dirt"
name                     : "LabeUrbe"
og_image                 :
repository               : "dmcpatrimonio/dmcpatrimonio.github.io"
search                   : true
search_full_content      : true
search_provider          : # lunr (default), algolia, google
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
title_separator          : "|"
words_per_minute         : 200

# Conversion and Output {{{1
# =====================
markdown                 : Pandoc
paginate                 : 5
paginate_path            : /page:num/
pandoc:
  extensions:
    - bibliography       : "_data/biblio.yaml"
    - csl                : "_lib/chicago-cv.csl"
    - defaults           : "_spec/defaults.yaml"
    - section-divs
permalink                :  /:categories/:title/
relative_links:
  enabled                : true
  collections            : true
sass:
  sass_dir: _sass
  style                  : compressed
timezone                 : "America/Sao_Paulo"

# Plugins {{{1
# =======
plugins: 
    # Required or recommended by Minimal Mistakes
  - jekyll-archives
  - jekyll-data
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-relative-links
    # Other
  - jekyll-pandoc
  - jekyll-seo-tag

# HTML Compression {{{1
# ================
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Archives {{{1
# ========
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type                   : jekyll-archives
  path                   : /categories/
tag_archive:
  type                   : jekyll-archives
  path                   : /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category             : archive-taxonomy
    tag                  : archive-taxonomy
    year                 : archive-taxonomy
  permalinks:
    category             : /categories/:name/
    tag                  : /tags/:name/
    year                 : /:year/

# Collections {{{1
# ===========
collections:
  posts:
    output   : true
    permalink: /:categories/:title/
  thing:
    output   : true
    permalink: /:collection/:title/
  creativework:
    output   : false
    permalink: /biblio/:title/
    sort_by  : issued[0].year
  event:
    output   : true
    permalink: /:collection/:title/
  grant:
    output   : false
    permalink: /:collection/:title/
    sort_by  : amount.validFrom
  organization:
    output   : true
    permalink: /linha/:title/
    sort_by  : title
  person:
    output   : true
    permalink: /membro/:title/
    sort_by  : familyName
  project:
    output   : true
    permalink: /projeto/:title/
    sort_by  : title

# Defaults {{{1
# ========
defaults:
  # Posts {{{2
  # -----
  - scope:
      path               : ""
      type               : "posts"
    values:
      #layout             : "single"
      author_profile     : true
      read_time          : true
      comments           : true
      share              : true
      related            : true
  # Thing {{{2
  # -----
  - scope:
      path               : ""
      type               : "thing"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/Thing"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
  # Biblio {{{2
  # ------
  - scope:
      path               : ""
      type               : "creativework"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/CreativeWork"
      type               : "PhysicalObject"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
  # Event {{{2
  # -----
  - scope:
      path               : ""
      type               : "event"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/Event"
      type               : "Event"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
  # Grant {{{2
  # -----
  - scope:
      path               : ""
      type               : "grant"
    values:
      layout             : "thing"
      itemtype           : "http://schema.org/MonetaryGrant"
      type               : "Event"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
  # Organization {{{2
  # ------------
  - scope:
      path               : ""
      type               : "organization"
    values:
      layout             : "organization"
      itemtype           : "http://schema.org/Organization"
      class              : "AgentClass"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true
  # Person {{{2
  # ------
  - scope:
      path               : ""
      type               : "person"
    values:
      layout             : "person"
      itemtype           : "http://schema.org/Person"
      class              : "Agent"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : false
  # Project {{{2
  # -------
  - scope:
      path               : ""
      type               : "project"
    values:
      layout             : "organization"
      itemtype           : "http://schema.org/ResearchProject"
      class              : "AgentClass"
      author_profile     : false
      read_time          : false
      comments           : false
      share              : true
      related            : true

# Footer {{{1
# ======
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/dmcpatrimonio

# vim: set foldmethod=marker :
